[package]
name = "rustsourcebundler"
version = "0.9.0"
authors = ["Leandro Lisboa Penz <lpenz@lpenz.org>"]
description = "Bundle the source code of a rust cargo crate in a single source file"
license = "Apache-2.0"
homepage = "https://github.com/lpenz/rust-sourcebundler"
repository = "https://github.com/lpenz/rust-sourcebundler.git"

[dependencies]
cargo_metadata = "0.5"
quote = "0.5"
rustfmt = "0.10"
syn = { version = "0.13", features = ["full", "extra-traits", "visit-mut"] }

